from  Data import reading_objects
from  POM.salary import salaries
import pytest

data_obj= reading_objects.read_data()
@pytest.mark.parametrize("data_",data_obj)
class Test_Module:

     def test_salary(self,_driver,data_):
          lp = salaries(_driver)
          lp.email_enter(data_)
          lp.continue_button()
          # time.sleep(2)
          lp.password_text(data_)
          # time.sleep(2)
          lp.submit_button()
          # time.sleep(2)
          lp.salary_click()
          # time.sleep(2)
          lp.job_title(data_)
          # time.sleep(2)
          lp.search_button()
          # time.sleep(2)
          lp.review_button()
          # time.sleep(2)
          lp.radio_button()
          # time.sleep(2)
          lp.Rekha(data_)
          # time.sleep(2)
          lp.suggession_s()
          # time.sleep(2)
          lp.next_button()
          # time.sleep(2)
          lp.year_s()
          # time.sleep(2)
          lp.monthl_y()
          # time.sleep(2)
          lp.salar_y(data_)
          # time.sleep(2)
          lp.country_rupees()
          # time.sleep(2)
          lp.country()
          # time.sleep(2)
          lp.years()
          # time.sleep(2)
          lp.monthly()
          # time.sleep(2)
          lp.bonus(data_)
          # time.sleep(2)
          lp.stocks(data_)
          # time.sleep(2)
          lp.profits(data_)
          # time.sleep(2)
          lp.sales(data_)
          # time.sleep(2)
          lp.tips(data_)
          # time.sleep(2)
          lp.employer()
          # time.sleep(2)
          lp.capgemini()
          # time.sleep(2)
          lp.joblevel(data_)
          # time.sleep(2)
          lp.number(data_)
          # time.sleep(2)
          lp.numbers(data_)
          # time.sleep(2)
          lp.location()
          # time.sleep(2)
          lp.Hyderabad()
          # time.sleep(2)
          lp.select()
          # time.sleep(2)
          lp.fulltime()
          # time.sleep(2)